soundspawn/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('', include('spa.urls')),
    path('admin/', admin.site.urls),
]

spa/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from .views import IndexView, DiscoverView, LoginView, LogoutView, SignupView, MeView
from .views import ProfileView, PlaylistView, AlbumView, SoundView, SearchView
from .views import PlaylistCreateView, AlbumCreateView, SoundCreateView, AlbumTrackView
from .views import EditProfileView, UploadSoundView, SoundDownloadStreamView, PlaylistTrackView
from .views import NewAlbumView, NewPlaylistView, PostCommentView, SearchAddTracksView
from .views import PlaylistViewSoundsJSON, AlbumViewSoundsJSON

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('discover/', DiscoverView.as_view(), name='discover'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

    path('me/', MeView.as_view(), name='me'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),

    path('playlist/create', PlaylistCreateView.as_view(), name='playlist_create'),
    path('album/create', AlbumCreateView.as_view(), name='album_create'),
    path('sound/create', SoundCreateView.as_view(), name='sound_create'),

     # rest
    path('playlist/<str:uuid>/sounds', PlaylistViewSoundsJSON.as_view(), name='playlist'),
    path('album/<str:uuid>/sounds', AlbumViewSoundsJSON.as_view(), name='album'),

    path('playlist/<str:uuid>/<str:sound_uuid>', PlaylistTrackView.as_view(), name='playlist_track'),
    path('album/<str:uuid>/<str:sound_uuid>', AlbumTrackView.as_view(), name='album_track'),

    path('playlist/<str:uuid>/', PlaylistView.as_view(), name='playlist'),
    path('album/<str:uuid>/', AlbumView.as_view(), name='album'),
    path('sound/<str:uuid>/', SoundView.as_view(), name='sound'),

    path('soundf/<str:uuid>/', SoundDownloadStreamView.as_view(), name='soundf'),

    path('me/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('uploadsound/', UploadSoundView.as_view(), name='upload_sound'),
    path('newalbum/', NewAlbumView.as_view(), name='new_album'),
    path('newplaylist/', NewPlaylistView.as_view(), name='new_playlist'),
    
    path('search/', SearchView.as_view(), name='search'),
    path('searchaddtracks/<str:obj_uuid>', SearchAddTracksView.as_view(), name='search_add_tracks'),

    path('comment/<str:sound_uuid>/', PostCommentView.as_view(), name='post_comment'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa/models.py
from django.db import models

from django.conf import settings

import uuid

from django.templatetags.static import static

class Upload(models.Model): # S3
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ProfilePictureMapping(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    upload = models.OneToOneField(Upload, on_delete=models.CASCADE)

class Sound(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    upload = models.OneToOneField(Upload, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_cover(self) :
        # if it has beed added to an album, return the album cover
        album = Album.objects.filter(sounds=self).first()
        if album is not None :
            return album.get_picture()

        pm = ProfilePictureMapping.objects.filter(user=self.user).first()
        if pm is None :
            return static('images/none.png')
        return pm.upload.file.url

class Album(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    sounds = models.ManyToManyField(Sound)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.OneToOneField(Upload, on_delete=models.CASCADE, null=True)

    def get_picture(self) :
        if self.picture is None :
            return static('images/none.png')
        return self.picture.file.url

class Playlist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    sounds = models.ManyToManyField(Sound)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.OneToOneField(Upload, on_delete=models.CASCADE, null=True)

    def get_picture(self) :
        if self.picture is None :
            return static('images/none.png')
        return self.picture.file.url

class History(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sound = models.ForeignKey(Sound, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sound = models.ForeignKey(Sound, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

spa/forms.py
from django import forms

from .models import Sound

class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {
                'class': 'form-control'
            }

class LoginForm(BootstrapForm):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class SignUpForm(BootstrapForm):
    username = forms.CharField(label='Username', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class EditProfileForm(BootstrapForm):
    username = forms.CharField(label='Username', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)

    new_pic = forms.ImageField(label='New Profile Picture', required=False)

class SoundUploadForm(BootstrapForm):
    # filter only audio file
    name = forms.CharField(label='Name', max_length=100)
    sound = forms.FileField(label='Sound', widget=forms.FileInput(attrs={'accept': 'audio/*'}))

class SoundEditForm(BootstrapForm):
    name = forms.CharField(label='Name', max_length=100)

class PlaylistCreateEditForm(BootstrapForm):
    name = forms.CharField(label='Name', max_length=100)
    pic = forms.ImageField(label='New Picture', required=False)
class AlbumCreateEditForm(BootstrapForm):
    name = forms.CharField(label='Name', max_length=100)
    pic = forms.ImageField(label='New Picture', required=False)

spa/views.py
from django.shortcuts import render

from django.views.generic import View

from django.contrib.auth import logout
from django.shortcuts import redirect

from django.contrib.auth import authenticate, login

from django.contrib.auth import get_user_model

from .forms import LoginForm, SignUpForm, EditProfileForm
from .forms import SoundUploadForm, SoundEditForm
from .forms import PlaylistCreateEditForm, AlbumCreateEditForm
from .models import Sound, Album, Upload
from .models import ProfilePictureMapping
from .models import History, Playlist, Comment

from django.http import HttpResponse

from django.http import FileResponse

from django.templatetags.static import static

# Create your views here.

class HTMXView(View) :
    def html_name(self):
        return "index"
    
    def pre_get(self, request):
        return ""
    
    def get(self, request, *args, **kwargs):
        redirect_url = self.pre_get(request)
        if redirect_url != "":
            return redirect(redirect_url)
        
        default_context = self.get_context(*args, **kwargs) | {
            "profile_picture_me": get_profile_picture(self.request.user) if self.request.user.is_authenticated else static('images/none.png')
        }

        if request.htmx:
            return render(request, f"{self.html_name()}.html", default_context)
        else :
            return render(request, f"{self.html_name()}_f.html", default_context)
        
    def get_context(self, *args, **kwargs) -> dict:
        return {}

class IndexView(HTMXView):
    def get_context(self, *args, **kwargs) -> dict:
        if self.request.user.is_authenticated:
            histories = History.objects.filter(user=self.request.user).order_by('-id')[:9]
            return {
                "histories": histories
            }
        return {}

class DiscoverView(HTMXView):
    def html_name(self):
        return "discover"
    
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        # logout from the session
        logout(request)
        return redirect('index')
    
class LoginView(HTMXView):
    def html_name(self):
        return "signin"
    
    def get_context(self, *args, **kwargs) -> dict:
        return {
            "form": LoginForm()
        }
    
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            # login the user
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                form.add_error(None, 'Invalid username or password')
        return render(request, 'signin_f.html', {
            "form": form
        })
    
class SignupView(HTMXView):
    def html_name(self):
        return "signup"
    
    def get_context(self, *args, **kwargs) -> dict:
        return {
            "form": SignUpForm()
        }
    
    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            # create user
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = get_user_model().objects.create_user(username, email, password)
            login(request, user)
            return redirect('index')
        return render(request, 'signup_f.html', {
            "form": form
        })
    
#############

def get_profile_picture(user):
    if user is None :
        return static('images/none.png')
    
    pro = ProfilePictureMapping.objects.filter(user=user).first()
    if pro is None:
        return static('images/none.png')
    
    return pro.upload.file.url
    
class ProfileView(HTMXView) :
    def html_name(self):
        return "profile"
    
    def get_user_from_request(self, *args, **kwargs):
        user = kwargs.get('username', None)
        if user is None:
            return None
        
        user = get_user_model().objects.filter(username=user).first()
        if user is None:
            return None
        
        return user
    
    def get_context(self, *args, **kwargs) -> dict:
        user = self.get_user_from_request(*args, **kwargs)

        if user is None:
            return {}
        
        eform = EditProfileForm()
        # put data in the form
        eform.fields['username'].initial = user.username
        eform.fields['email'].initial = user.email

        sounds = Sound.objects.filter(user=user)
        albums = Album.objects.filter(user=user)
        playlists = Playlist.objects.filter(user=user)

        return {
            "profile_picture": get_profile_picture(user),
            "profile_user": user,

            "sounds": sounds,
            "albums": albums,
            "playlists": playlists,

            "edit_form": eform,

            "sound_count": len(sounds),
            "album_count": len(albums),
            "playlist_count": len(playlists)
            
        }
    
class MeView(ProfileView) :
    def html_name(self):
        return "profile"
    
    def get_user_from_request(self, *args, **kwargs):
        return self.request.user
    
    def pre_get(self, request):
        if request.user.is_anonymous:
            return 'login'
        return ""
    
#############

def _get_album_or_playlist_context(request, is_playlist, *args, **kwargs):
    uuid = kwargs.get('uuid', None)
    if uuid is None :
        return {}
    try :
        if is_playlist :
            obj = Playlist.objects.get(id=uuid)
        else :
            obj = Album.objects.get(id=uuid)
    except :
        return {}
        
    if obj is None :
        return {}
    
    if is_playlist :
        # PLAYLIST IS PRIVATE
        if obj.user != request.user:
            return {}
    
        eform = PlaylistCreateEditForm()
    else :
        eform = AlbumCreateEditForm()
    # put data in the form
    eform.fields['name'].initial = obj.name

    sounds = obj.sounds.all()

    return {
        ("playlist" if is_playlist else "album"): obj,
        "edit_form": eform,
        "tracks": sounds,
        "is_playlist": is_playlist
    }

class PlaylistView(HTMXView) :
    def html_name(self):
        return "playlist"
    
    def get_context(self, *args, **kwargs) -> dict:
        return _get_album_or_playlist_context(self.request, True, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('login')

        playlist = kwargs.get('uuid', None)
        if playlist is None:
            return redirect('index')
        
        playlist = Playlist.objects.get(id=playlist)
        if playlist is None:
            return redirect('index')
        
        if request.user != playlist.user:
            return redirect('index')
        
        form = PlaylistCreateEditForm(request.POST, request.FILES)
        if form.is_valid():
            playlist.name = form.cleaned_data['name']

            # pic upload
            pic = form.cleaned_data['pic']
            if pic :
                upload = Upload.objects.create(user=request.user, file=pic)
                playlist.picture = upload
            playlist.save()
            
            return redirect('playlist', uuid=playlist.id)
        
        return redirect('playlist', uuid=playlist.id)
    
class AlbumView(HTMXView) :
    def html_name(self):
        return "album"
    
    def get_context(self, *args, **kwargs) -> dict:
        return _get_album_or_playlist_context(self.request, False, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('login')

        album = kwargs.get('uuid', None)
        if album is None:
            return redirect('index')
        
        album = Album.objects.get(id=album)
        if album is None:
            return redirect('index')
        
        if request.user != album.user:
            return redirect('index')
        
        form = AlbumCreateEditForm(request.POST, request.FILES)
        if form.is_valid():
            album.name = form.cleaned_data['name']

            # pic upload
            pic = form.cleaned_data['pic']
            if pic :
                upload = Upload.objects.create(user=request.user, file=pic)
                album.picture = upload
            album.save()
            
            return redirect('album', uuid=album.id)
        
        return redirect('album', uuid=album.id)
    
class SoundView(HTMXView) :
    def html_name(self):
        return "sound"
    
    def get_context(self, *args, **kwargs) -> dict:
        sound = kwargs.get('uuid', None)
        if sound is None:
            return {}
        
        try :
            sound = Sound.objects.get(id=sound)
        except Sound.DoesNotExist:
            return {}

        if sound is None:
            return {}
        
        eform = SoundEditForm()
        # put data in the form
        eform.fields['name'].initial = sound.name

        # comments
        comments = Comment.objects.filter(sound=sound).order_by('-created_at')

        return {
            "sound": sound,
            "profile_picture_uploader": get_profile_picture(sound.user),
            "edit_form": eform,

            "comments": comments
        }
    
    def post(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('login')

        sound = kwargs.get('uuid', None)
        if sound is None:
            return redirect('index')
        
        try :
            sound = Sound.objects.get(id=sound)
        except Sound.DoesNotExist:
            return redirect('index')
        
        if request.user != sound.user:
            return redirect('index')
        

spa/templates/add_track_search.html
{% for s in sounds %}
<tr hx-target="#content">
	<td><img id="song-cover" src="{{ s.get_cover }}" alt="Album Icon" class="rounded-2" style="width: 50px; height: 50px;"></td>
	<td>{{ s.name }}</td>
	<td>{{ s.user.username }}</td>
	<td>
		<!-- add button -->

		{% if is_playlist %}
		<form class="d-flex me-5">
			<button class="btn btn-danger" data-bs-dismiss="modal" type="submit" hx-put="{% url 'playlist_track' object.id s.id %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>Add</button>
		</form>
		{% else %}
		<form class="d-flex me-5">
			<button class="btn btn-danger" data-bs-dismiss="modal" type="submit" hx-put="{% url 'album_track' object.id s.id %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>Add</button>
		</form>
		{% endif %}
	</td>
</tr>
{% endfor %}

spa/templates/album_create.html
<div class="form-container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <form action="/newalbum/" method="post" enctype="multipart/form-data" style="background-color: #D8B9B2; padding: 40px; border-radius: 10px; width: 400px;">
        <div style="margin-bottom: 20px;">
            <label for="song-name" style="font-weight: bold; font-size: 18px;">Album name :</label>
            <input id="id_name" name="name" type="text" name="songname" style="width: 100%; padding: 10px; border-radius: 5px; border: 1px solid #ccc; font-size: 16px;">
        </div>
        <div style="margin-bottom: 20px; font-weight: bold; font-size: 18px;">Upload Your Picture Here :</div>

        {% csrf_token %}

        <div style="background-color: #7D2A26; color: white; width: 100%; height: 150px; display: flex; align-items: center; justify-content: center; border-radius: 10px; cursor: pointer; position: relative;">
            <input id="id_pic" name="pic" type="file" name="file" style="opacity: 0; position: absolute; width: 100%; height: 100%; cursor: pointer;">
            <span id="file-chosen" style="font-size: 36px; color: #FFFFFF; z-index: 1;">+</span>
        </div>

        <div style="text-align: center; margin-top: 30px;">
            <button type="submit" style="padding: 12px 25px; background-color: #7D2A26; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">Submit</button>
        </div>
    </form>
</div>

<script>
const idPic = document.getElementById('id_pic');

const fileChosen = document.getElementById('file-chosen');

idPic.addEventListener('change', function(){
    fileChosen.textContent = this.files[0].name;
    fileChosen.style.fontSize = '16px';
})
</script>

<script>  
document.title = "New Album - SOUND SPAWN";    
</script>

spa/templates/discover.html
<h1>Discover</h1>

{% lorem 23 p %}

spa/templates/index.html
{% load static %}
<div class="mt-4">
{% if user.is_authenticated %}

<!-- Welcome Back text with gradient background -->
<div class="text-white p-4 rounded-2" style="background-color: #631919">
	<h1 class="fw-bold">Welcome Back, {{ user.username }}</h1>
	<p class="fs-4">You can listen to your favorite music here.</p>
</div>

<h1 class="fw-bold mt-4">Last Played</h1>

{% if histories %}
<div class="row">
{% for history in histories %}
	<div class="col-4" hx-target="#content">
		<a href="{% url 'sound' history.sound.id %}" hx-get="{% url 'sound' history.sound.id %}" hx-push-url="true">
			<img src="{{ history.sound.get_cover }}" alt="sound Icon" style="width: 250px; height: 250px">
			<p class="fs-4 fw-bold mt-2 text-decoration-none text-black">{{history.sound.name}}</p>
		</a>
	</div>
{% endfor %}
</div>
{% else %}

<p>No history</p>

{% endif %}

{% else %}

<!-- promotional text of our app Soundspawn-->

<div class="position-absolute w-100 h-100" style="left:0;top:0;">
	<img class="w-100 rounded-3" style="filter: brightness(30%);" src="{% static 'images/cover.jpeg' %}" alt="Soundspawn Cover">
	<!-- center text -->
	<div class="position-absolute top-50 start-50 translate-middle text-white">
		<h1 class="fw-bold text-center">Discover Your Next Favorite Song, Anytime, Anywhere — Dive into the Soundtrack of Your Life.</h1>
		<p class="fs-4 text-center">SOUND SPAWN is a music streaming service that allows you to listen to music for free. You can listen to any music you want, anytime you want, and anywhere you want. You can also create your own playlist or create your own album.</p>
		<!-- two buttons -->
		<div class="d-flex justify-content-center mt-4">
			<a href="{% url 'signup' %}" class="btn btn-danger btn-lg" style="box-shadow: 0 0 30px var(--box-shadow-color); --box-shadow-color: #dc3545;">Sign up for free</a>
		</div>
	</div>
</div>
{% endif %}

</div>

spa/templates/playlist_create.html
<div class="form-container" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <form action="/newplaylist/" method="post" enctype="multipart/form-data" style="background-color: #D8B9B2; padding: 40px; border-radius: 10px; width: 400px;">
        <div style="margin-bottom: 20px;">
            <label for="song-name" style="font-weight: bold; font-size: 18px;">Playlist name :</label>
            <input id="id_name" name="name" type="text" name="songname" style="width: 100%; padding: 10px; border-radius: 5px; border: 1px solid #ccc; font-size: 16px;">
        </div>
        <div style="margin-bottom: 20px; font-weight: bold; font-size: 18px;">Upload Your Picture Here :</div>

        {% csrf_token %}

        <div style="background-color: #7D2A26; color: white; width: 100%; height: 150px; display: flex; align-items: center; justify-content: center; border-radius: 10px; cursor: pointer; position: relative;">
            <input id="id_pic" name="pic" type="file" name="file" style="opacity: 0; position: absolute; width: 100%; height: 100%; cursor: pointer;">
            <span id="file-chosen" style="font-size: 36px; color: #FFFFFF; z-index: 1;">+</span>
        </div>

        <div style="text-align: center; margin-top: 30px;">
            <button type="submit" style="padding: 12px 25px; background-color: #7D2A26; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">Submit</button>
        </div>
    </form>
</div>

<script>
const idPic = document.getElementById('id_pic');

const fileChosen = document.getElementById('file-chosen');

idPic.addEventListener('change', function(){
    fileChosen.textContent = this.files[0].name;
    fileChosen.style.fontSize = '16px';
})
</script>

<script>
document.title = "New Playlist - SOUND SPAWN";    
</script>

spa/templates/playlist_create_f.html
{% extends 'base.html' %}

{% block content %}
	{% include "playlist_create.html" %}
{% endblock content %}

spa/templates/profile_f.html
{% extends 'base.html' %}

{% block content %}
	{% include "profile.html" %}
{% endblock content %}

spa/templates/search.html
<div hx-target="#content">
	<h1>Search Results : "{{ query }}"</h1>

	{% if empty %}
		<p>No results found</p>
	{% endif %}

	{% if sounds %}
	<div class="row">
		<h1>Tracks</h1>
		{% for sound in sounds %}
			<div class="col-4">
				<a href="{% url 'sound' sound.id %}" hx-get="{% url 'sound' sound.id %}" hx-push-url="true">
					<img src="{{ sound.get_cover }}" alt="sound Icon" style="width: 250px; height: 250px">
					<p class="fs-4 fw-bold mt-2 text-decoration-none text-black">{{sound.name}}</p>
				</a>
			</div>
		{% endfor %}
	</div>
	{% endif %}

	{% if albums %}
	<div class="row">
		<h1>Albums</h1>
		{% for album in albums %}
			<div class="col-4">
				<a href="{% url 'album' album.id %}" hx-get="{% url 'album' album.id %}" hx-push-url="true">
					<img src="{{ album.get_picture }}" alt="Album Icon" style="width: 250px; height: 250px">
					<p class="fs-4 fw-bold mt-2 text-decoration-none text-black">{{album.name}}</p>
				</a>
			</div>
		{% endfor %}
	</div>

	{% endif %}

	{% if users %}
	<div class="row">
		<h1>Users</h1>
		{% for user in users %}
			<div class="col-4">
				<a href="{% url 'profile' user.user.username %}" hx-get="{% url 'profile' user.user.username %}" hx-push-url="true">
					<img src="{{ user.profile_picture }}" alt="User Icon" style="width: 250px; height: 250px">
					<p class="fs-4 fw-bold mt-2 text-decoration-none text-black">{{user.user.username}}</p>
				</a>
			</div>
		{% endfor %}
	</div>
	{% endif %}
</div>

<script>
document.title = "Search \"{{ query }}\" - SOUND SPAWN";    
</script>

spa/templates/search_f.html
{% extends 'base.html' %}

{% block content %}
	{% include "search.html" %}
{% endblock content %}

spa/templates/signup_f.html
{% extends 'base.html' %}

{% block content %}
	{% include "signup.html" %}
{% endblock content %}

spa/templates/sound.html
{% load static %}

{% if sound %}

<div>
	<div style="background-color: #FF7373; height: 300;">
		<!-- big profile picture -->
		<div class="text-white d-flex p-4 pt-5">
			<img src="{{ sound.get_cover }}" alt="Profile Picture" class="rounded" style="width: 200px; height: 200px">
			<div class="ms-5" hx-target="#content">
				<h1 class="bg-danger p-2 my-auto">{{sound.name}}</h1>
				<div>
					Uploaded by <a class="text-white fw-bold" href="{% url 'profile' sound.user.username %}" hx-get="{% url 'profile' sound.user.username %}" hx-push-url="true">{{ sound.user.username }}</a>
					on {{sound.created_at}}
				</div>
				<button
					onclick="playMusic('/soundf/{{ sound.id }}/', '{{ sound.get_cover }}', '{{ sound.name }}', '{{ sound.user.username }}', '/sound/{{ sound.id }}/', '/profile/{{ sound.user.username }}/')"
					class="btn btn-success mt-2"
				><i class="bi bi-play-fill"></i>Play</button>
				{% if sound.user == user %}
					<button class="btn btn-danger mt-2" data-bs-toggle="modal" data-bs-target="#edit-song-modal">Edit</button>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<!-- Comment Section -->
<div>
	<h1>Comments</h1>
	<div id="comments">
		{% include "comment_section.html" %}
	</div>
	{% if user.is_authenticated %}
		<form method="post" action="{% url 'post_comment' sound.id %}" hx-post="{% url 'post_comment' sound.id %}" hx-target="#comments">
			{% csrf_token %}
			<div class="mb-3">
				<label for="comment" class="form-label">Comment</label>
				<textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
			</div>
			<button type="submit" class="btn btn-danger">Submit</button>
		</form>
	{% endif %}
</div>

<!-- Edit Modal -->
<div class="modal fade" id="edit-song-modal" tabindex="-1" aria-labelledby="edit-song-modal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="exampleModalLabel">Edit Track</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="post" action="" enctype="multipart/form-data">
					{% csrf_token %}
					{% if error %}
					<div class="alert alert-danger" role="alert">
						{{ error }}
					</div>
					{% endif %}
					<div class="mb-3">
						{{ edit_form }}
					</div>

					<div><div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
						<input type="submit" class="btn btn-danger" value="Save Changes">
					</div></div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
document.title = "{{ sound.name }} - SOUND SPAWN";    
</script>

{% else %}

<h1>Track is not found</h1>

{% endif %}